### PR TITLE
160 fusion definitiva

### PR DESCRIPTION
**Pull request by ervinj1998**
corrigiendo, conflictos

### CODE REVIEW

**Comment by ervinj1998** [comment]
ready

**Comment by Hawaiideveloper** [comment]
now testing

**Comment by Hawaiideveloper** [comment]
@ervinj1998 please show me this link after you do `yarn start`

http://localhost:3000/users

**Comment by ervinj1998** [comment]
mira esto.

**Comment by Hawaiideveloper** [comment]
try another screenshot.  this one is still loading

Screen Shot 2020-10-21 at 9 06 20 PM

**Comment by Hawaiideveloper** [comment]
@ervinj1998 ^

**Comment by ervinj1998** [comment]
@Hawaiideveloper 
Captura de pantalla de 2020-10-21 21-03-55

**Comment by Hawaiideveloper** [comment]
no
the users page so we can see all the users

**Comment by Hawaiideveloper** [comment]
http://localhost:3000/users

**Comment by Hawaiideveloper** [comment]
@ervinj1998 ^

**Comment by Hawaiideveloper** [comment]
what happened to everyone's photo?
Screen Shot 2020-10-21 at 9 10 16 PM

**Comment by Hawaiideveloper** [comment]
we use to be able to see everyone's photo here

**Pull request merged**
