### PR TITLE
Profile photo upload

### PR DESCRIPTION
**Pull request by ervinj1998**
En esta rama se agrega la nueva funcionalidad de agregar una foto de perfil o actualizarla en la opcion edit profile, sin embargo actualmente el mensaje solo se ve en consola. tambien ubo correcion en espacios en blanco, y agregamos un par de comentarios en algunas parte del codigo.

### CODE REVIEW

**Comment by Hawaiideveloper** [comment]
I do not see anything after uploading...  Am I suppose to see the photo?  Where can I find the photo?

**Comment by Hawaiideveloper** [comment]
Screen Shot 2020-10-10 at 10 17 49 PM

**Comment by Hawaiideveloper** [comment]
Screen Shot 2020-10-10 at 10 20 46 PM
Screen Shot 2020-10-10 at 10 17 49 PM

**Comment by Hawaiideveloper** [comment]
Any suggestions to see where we can find the photo from the front-end?

**Comment by ervinj1998** [comment]
the photo is only uploaded and sent to the server, it is not currently showing in the profile, not yet

**Comment by Hawaiideveloper** [comment]
Awesome.   So its sent to the back-end?

Where there any updates to the node**API**?

If not, I am prepared to merge, but we need to be clear there where no changes to the [back-end..](https://github.com/Hawaiideveloper/nodeJS_SocialMediaSite)

**Comment by Hawaiideveloper** [comment]
if everything is cool, let me know?

**Comment by Hawaiideveloper** [comment]
I have not heard back from you.  Now proceeding with the tests

**Comment by Hawaiideveloper** [comment]
pushing to alpha_branch first

**Comment by ervinj1998** [comment]
La foto se envia al backend al "Servidor" en forma binaria y la almacena para luego ocuparla o mostrarla.

**Pull request merged**
