### PR TITLE
adds thumbnails so you can see all users

### PR DESCRIPTION
**Pull request by Hawaiideveloper**
Trying to fix thumbnails

### CODE REVIEW

**Comment by Hawaiideveloper** [comment]
it has a render method and repairs it so we can see all user thumbnails

**Comment by Hawaiideveloper** [comment]
ready to test on master and then I will move it to alpha, and finally I will need you @ervinj1998 to pull my new changes into your project. and call it chapter 160.5

**Comment by Hawaiideveloper** [comment]
screen shots attached:
Screen Shot 2020-10-21 at 9 10 16 PM
Screen Shot 2020-10-21 at 10 28 00 PM
Screen Shot 2020-10-21 at 10 28 09 PM
Screen Shot 2020-10-21 at 10 28 16 PM
Screen Shot 2020-10-21 at 10 28 24 PM
Screen Shot 2020-10-21 at 10 28 34 PM
Screen Shot 2020-10-21 at 10 28 42 PM

Please see screenshots above all has been tested

**Comment by ervinj1998** [comment]
that is, in your repositories?

**Pull request merged**
